// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Time use in Sweden - Statistics Sweden.
type TimeUseInSwedenDataset struct {
	TimeAllocationWeekdayWomen    float64 `json:"time_allocation_weekday_women"`
	TimeAllocationWeekendWomen    float64 `json:"time_allocation_weekend_women"`
	TimeAllocationWeekdayMen      float64 `json:"time_allocation_weekday_men"`
	TimeAllocationWeekendMen      float64 `json:"time_allocation_weekend_men"`
	TimeAllocationAverageDayWomen float64 `json:"time_allocation_average_day_women"`
	TimeAllocationAverageDayMen   float64 `json:"time_allocation_average_day_men"`
}
